### ISSUE TITLE
only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by mjseyyedi** [alcmoraes/react-leaflet-animated-marker#1]
I want to use your library, but I get this error. how can I handle this?

> Uncaught (in promise) Error: only one instance of babel-polyfill is allowed

**Comment by anarqz** [comment]
Really sorry for the delay in my response @mjseyyedi . I've never heard about this error before. Did you manage to solve it?

**Comment by mjseyyedi** [comment]
yes, I did that period of time. but currently I'm not using leaflet anymore
